Add Dtos for Client and PetSitter endpoints, AB#46
patipec/PetSupport pull request #6
Opened 2020-12-04 11:43 UTC by Lukas-Stanleyy

Please check the Dtos.

2020-12-04 16:04 UTC, zdulak requested changes
Add FindPetSitterLongForm and FindPetSitterShortForm dtos

2020-12-04 16:04 UTC, zdulak commented on backend/PetSupport.API/Dtos/OutDtos/BookingMessageFullDTO.cs
> +        public string Message { get; set; }
Change Client type to ClientDto and create adequate ClientDto type

2020-12-04 16:04 UTC, zdulak commented on backend/PetSupport.API/Dtos/InDtos/CreatePetsitterDTO.cs
> +
Good idea in todo

2020-12-09 16:50 UTC, Lukas-Stanleyy commented on backend/PetSupport.API/Dtos/OutDtos/BookingMessageFullDTO.cs
> +        public string Message { get; set; }
Done

2020-12-09 16:50 UTC, closed without merging